pantalla: 
 ancho: 800 
 alto: 600 

configuracion: 
 vel_personaje : 3 
 margen_scroll : 30

tipos: 
   - nombre: arbol
     imagen: path/a/imagen.png
   - nombre: casa
     imagen: path/a/imagen.png