pantalla: 
 ancho: 800
 alto: 600

configuracion: 
 vel_personaje : 3 
 margen_scroll : 100

tipos: 
   - nombre: arbol
     imagen: assets/terrain.png
     ancho: 1
     alto: 1
     pixel_ref_x: 0
     pixel_ref_y: 0
   - nombre: castillo
     imagen: assets/castillo.png
     ancho: 2
     alto: 2 
     pixel_ref_x: 0
     pixel_ref_y: 0
   - nombre: soldado
     imagen: path/a/imagen.png 
     ancho: 1
     alto: 1
     pixel_ref_x: 0
     pixel_ref_y: 0
     fps: 10 
     delay: 5
   - nombre: tierra
     imagen: assets/Tiles/tierra.png
     ancho: 1
     alto: 1
     pixel_ref_x: 0
     pixel_ref_y: 0
   - nombre: agua
     imagen: assets/Tiles/agua.png
     ancho: 1
     alto: 1
     pixel_ref_x: 0
     pixel_ref_y: 0
   - nombre: juana_de_arco
     imagen: assets/GoblinWalk.png
     ancho: 1
     alto: 1
     pixel_ref_x: 0
     pixel_ref_y: 0
     fps: 20
     delay: 0
   - nombre: molino
     imagen: assets/windmill.png
     ancho: 2
     alto: 1
     pixel_ref_x: 15
     pixel_ref_y: 0
     fps: 5
     delay: 0

escenario:
     nombre: orleans 
     size_x: 100 
     size_y: 100 
     entidades:  
        - {x: 0, y: 0, tipo: agua} 
        - {x: 15, y: 20, tipo: arbol} 
        - {x: 10, y: 15, tipo: arbol} 
        - {x:  5, y:  5, tipo: castillo}
        - {x: 1, y: 5, tipo: molino}
        - {x: 7, y: 7, tipo: arbol}
        - {x: 1, y: 0, tipo: agua}
        - {x: 0, y: 1, tipo: agua}
        - {x: 1, y: 1, tipo: agua}
        - {x: 8, y: 10, tipo: arbol}
        - {x: 8, y: 12, tipo: arbol}
        - {x: 9, y: 13, tipo: arbol}
        - {x: 9, y: 14, tipo: arbol}
        - {x: 9, y: 11, tipo: arbol}
        - {x: 9, y: 15, tipo: arbol}
        - {x: 9, y: 16, tipo: arbol}
        - {x: 9, y: 17, tipo: arbol}
        - {x: 9, y: 18, tipo: arbol}
        - {x: 9, y: 19, tipo: arbol}
        - {x: 9, y: 20, tipo: arbol}
        - {x: 9, y: 21, tipo: arbol}


protagonista: 
     tipo: juana_de_arco
     x: 8
     y: 8
